### ISSUE TITLE
[FEAT]: ui/home - top Instructor

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#18]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/2e501faa-f228-4676-a981-12514f808e89)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it

**Comment by sub1120** [comment]
Assigned to @Vinay-Pratap-Singh
