### ISSUE TITLE
[FEAT]: ui/home - trusted companies

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#19]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/d0558dec-3696-463b-b3dc-6f83685f2a60)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it
