### ISSUE TITLE
[FEAT]: ui/home - become a instructor

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#20]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/583db164-b317-4c24-8755-64081b0659bf)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it

**Comment by sub1120** [comment]
Assigned to @Vinay-Pratap-Singh.
