### ISSUE TITLE
[FEAT]: ui/home - recently added courses

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#21]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/3bd5cfce-b863-4640-a631-a57e6113d7b5)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it
