### ISSUE TITLE
[FEAT]: ui/home - featured courses

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#22]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/f2e553fd-e05b-4b6d-80cf-25e934f5a7fa)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it
