### ISSUE TITLE
[FEAT]: ui/home - best selling courses

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#23]
### Summary
NA
### Answer following questions?
1. Is your feature related to FrontEnd? Yes
2. Is your feature related to Backend? No
3. Is your feature related to API Integration? No
### Resources
![image](https://github.com/lmsGenie/lmsGenie/assets/43786036/557fa659-44af-44a6-9a47-fb3e3078538b)

**Comment by Vinay-Pratap-Singh** [comment]
I am working on it
