### ISSUE TITLE
[Fix]: hover background color in footer section

### ISSUE THREAD

**Issue by MTouthang** [lmsGenie/lms-app#62]
**Describe the bug**
On hover, the background colour in the footer section of "App Store" and "Play Store" should change to orange, like the rest of the icons in the footer section

**To Reproduce**
1. Go to the footer section
2. Hover on the "App Store" and "Play Store" icons
3. The background colour of the icons will not change to orange, compared to the footer social link icon section inside the footer itself.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sub1120** [comment]
Done
