### ISSUE TITLE
[FEAT]: Create a Error Page

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/lms-app#69]
**Is your feature request related to a problem? Please describe.**
As we visit any wrong path in website, it shows next.js default error page.
 
![image](https://github.com/lmsGenie/client/assets/43786036/a76e07a0-ec66-47f8-8574-416081e02c19)

**Describe the solution you'd like**
We will make our custom error page.

**Describe alternatives you've considered**
NA

**Additional context**
![46_404_Error Pages](https://github.com/lmsGenie/client/assets/43786036/1ee64cd9-98f1-4ac2-8cb6-134dc854989e)

**Comment by shivamvijaywargi** [comment]
I am working on this

**Comment by shivamvijaywargi** [comment]
It has been 2 weeks, status please?

**Comment by sub1120** [comment]
> It has been 2 weeks, status please?

Sorry for the delay, I started working on it yesterday. I will complete it soon.
