### ISSUE TITLE
[FEAT]: ui/contact - connect with us

### ISSUE THREAD

**Issue by Vinay-Pratap-Singh** [lmsGenie/lms-app#74]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create the ui

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="463" alt="image" src="https://github.com/lmsGenie/client/assets/85826727/f8f43d01-becb-496d-a16f-5cd034780bf9">

**Comment by Vinay-Pratap-Singh** [comment]
Working ...

**Comment by sub1120** [comment]
Created a common issue for contact us page - #122.
