### ISSUE TITLE
[FEAT]: ui/contact - our branches

### ISSUE THREAD

**Issue by Vinay-Pratap-Singh** [lmsGenie/lms-app#75]
**Is your feature request related to a problem? Please describe.**
Yes related to UI

**Describe the solution you'd like**
Contact us page main section

**Additional context**
<img width="461" alt="image" src="https://github.com/lmsGenie/client/assets/85826727/6e8eb9bd-b8ac-443d-b34e-67fad5332149">

**Comment by Vinay-Pratap-Singh** [comment]
Working on it...

**Comment by sub1120** [comment]
Created a common issue for contact us page - #122.
