### ISSUE TITLE
[FEAT]: ui/contact - contact us

### ISSUE THREAD

**Issue by Vinay-Pratap-Singh** [lmsGenie/lms-app#76]
**Is your feature request related to a problem? Please describe.**
Yes for the contact us form

**Describe the solution you'd like**
Create the ui for the contact us form

**Additional context**
<img width="462" alt="image" src="https://github.com/lmsGenie/client/assets/85826727/50f1d449-a4f5-4237-b1f4-2a46082e7bee">

**Comment by Vinay-Pratap-Singh** [comment]
Working on it ...

**Comment by sub1120** [comment]
Created a common issue for contact us page - #122.
