### ISSUE TITLE
[FEAT]: ui/contact - google map

### ISSUE THREAD

**Issue by Vinay-Pratap-Singh** [lmsGenie/lms-app#77]
**Is your feature request related to a problem? Please describe.**
For google map in ui

**Describe the solution you'd like**
Will embed the google map in contact us page

**Additional context**
<img width="464" alt="image" src="https://github.com/lmsGenie/client/assets/85826727/aaa9484d-8faa-4966-ab4d-a245666b4d68">

**Comment by Vinay-Pratap-Singh** [comment]
Working on it ...

**Comment by sub1120** [comment]
Created a common issue for contact us page - #122.
